### ISSUE TITLE
Modmail ignoring DMs

### ISSUE THREAD

**Issue by teddyHV11** [CTK-WARRIOR/Discord-Modmail-Bot#1]
# Background
I set the modmail up on Heroku, it worked fine for a day, after a day it stopped working.

# Issue 

Just set up the modmail, it went online. I set the server up and DMed the bot, it completely ignored by DMs. I used the -open command to create a thread and spoke in the the modmail channel, it did DM me; but when I DMed the bot back it did nothing.

**Comment by CTK-WARRIOR** [comment]
it should be working fine now
