### ISSUE TITLE
People who dm the bot images we can't see it   

### ISSUE THREAD

**Issue by shawn3308** [CTK-WARRIOR/Discord-Modmail-Bot#10]
People who dm the bot images we can't see it  . the bot doesn't post image's could you add that were people can send images too

**Comment by CTK-WARRIOR** [comment]
because it do not support attachments

**Comment by shawn3308** [comment]
Will it support it in feature

**Comment by iMu7aMMaD** [comment]
Can you add if the user sends attachments then the bot send it back?
