### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by sauravpandeyy** [CTK-WARRIOR/Discord-Modmail-Bot#11]
how to run the bot what's the command for that? please reply!!

**Comment by Sauravlol** [comment]
plss help me!!!

**Comment by Yonle** [comment]
First off, Do `?setup` or `[prefix]setup`

**Comment by Yonle** [comment]
Also, Try DM the bot (Notice: I didn't test it yet but goodluck)

**Comment by mastercuber55** [comment]
> how to run the bot what's the command for that? please reply!!

Goto #Shell And Type `node index.js` then Press **Enter**

**Comment by koko123448** [comment]
![image](https://user-images.githubusercontent.com/74993091/138071630-9fa135cf-2b68-499b-80a6-573a1c30167d.png)
xd

**Comment by CTK-WARRIOR** [comment]
Fixed
