### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by folliejester** [CTK-WARRIOR/Discord-Modmail-Bot#6]
(node:7496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined

if(receivedMessage.channel.parentID == category.id) {

**Comment by GamingWithEPMninjaYT** [comment]
Hello! This is a simple fix: I just changed "category.id" to my guild ID in quotations (""), and it works fine! It seems the only error is that the bot won't send messages from my server to the user.
