### ISSUE TITLE
modmail ignoring dms

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [CTK-WARRIOR/Discord-Modmail-Bot#7]
hi
so i forked your repo, and set it up
one issue.. it ignores dms
i can open a thread from the server, but not through dms

**Comment by CTK-WARRIOR** [comment]
is there any error?

**Comment by SirEpiclyAmazing** [comment]
no

**Comment by CTK-WARRIOR** [comment]
try again, i updated codes
